### ISSUE TITLE
os.get_terminal_size().columns "OSError: [Errno 25] Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by BylgakovAN** [benfred/py-spy#122]
Hi all.
Its a bug?
I just get the screen size

```
python3 -V
Python 3.6.8

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

```    
Press Control-C to quit, or ? for help.

process 13654 ended
Traceback (most recent call last):
  File "./os_terminal.py", line 11, in <module>
    sys.exit(main())
  File "./os_terminal.py", line 7, in main
    res_displ_term = os.get_terminal_size().columns
OSError: [Errno 25] Inappropriate ioctl for device

```

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os,sys

def main(argv=sys.argv):
	res_displ_term = os.get_terminal_size().columns
	print(res_displ_term)

if __name__ == "__main__":
	sys.exit(main())
```

**Comment by benfred** [comment]
When you get py-spy to create the python program, it doesn't attach it to a terminal =(. You will have to run your python program yourself in a terminal, and then pass the pid to py-spy instead.
