### ISSUE TITLE
"pip install py-spy" fails on RHEL 7.6 ppc64le

### ISSUE THREAD

**Issue by amitsadaphule** [benfred/py-spy#233]
I am trying to install py-spy on my RHEL 7.6 ppc64le machine. But it keeps throwing the following error:
```
# pip3.7 install py-spy
ERROR: Could not find a version that satisfies the requirement py-spy (from versions: none)
ERROR: No matching distribution found for py-spy
```

Going into verbose mode gives many messages of the form:
_Skipping link: none of the wheel's tags match: ._
Pasting part of the log in verbose mode:
```
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_i686, py3-none-manylinux1_i686: https://files.pythonhosted.org/packages/11/f0/20a67fd3dfe1a693bfb37b785615e4a468558d1f4607e8498fd2a959eb49/py_spy-0.3.3-py2.py3-none-manylinux1_i686.whl#sha256=72eb5c0495b050e6e9424ea373ff7245a01554e98f218d89f8f979c0cd762681 (from https://pypi.org/simple/py-spy/)
  Skipping link: none of the wheel's tags match: py2-none-manylinux1_x86_64, py3-none-manylinux1_x86_64: https://files.pythonhosted.org/packages/8e/a7/ab45c9ee3c4654edda3efbd6b8e2fa4962226718a7e3e3be6e3926bf3617/py_spy-0.3.3-py2.py3-none-manylinux1_x86_64.whl#sha256=e9d6946741c267fe82aef18d2fc1e095a90a83fb5f3d9fc89b0f20a39613a639 (from https://pypi.org/simple/py-spy/)
  Skipping link: none of the wheel's tags match: py2-none-win_amd64, py3-none-win_amd64: https://files.pythonhosted.org/packages/b7/34/52f5898e58a69257afeef18f97701d99942959f5abb9f8b31676055ee6b7/py_spy-0.3.3-py2.py3-none-win_amd64.whl#sha256=a165d444cfbf24cdcdfe8cdaa858a179e1fae43adcb912e5efb3151362f67aa8 (from https://pypi.org/simple/py-spy/)
Given no hashes to check 0 links for project 'py-spy': discarding no candidates
ERROR: Could not find a version that satisfies the requirement py-spy (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-y0b1v6m_'
ERROR: No matching distribution found for py-spy
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for py-spy
```

**Comment by amitsadaphule** [comment]
Build and install from source worked for me, so closing the task. Adding the steps for other's sake:
yum install -y cargo
git clone https://github.com/benfred/py-spy.git
cd py-spy/
python3.7 setup.py bdist_wheel
pip3.7 install dist/py_spy-0.3.3-cp37-cp37m-linux_ppc64le.whl

**Comment by benfred** [comment]
We're distributing binary wheels only - and ppc64le isn't supported right now. I don't believe that distributing ppc64le binaries is supported on pip/pypi , so I don't think we can easily add this.

Like you found out - the easiest way to get this going for ppc64le is to build from source =(

**Comment by amitsadaphule** [comment]
Thanks @benfred for the feedback!
