### ISSUE TITLE
Error: receiving on a closed channel

### ISSUE THREAD

**Issue by messense** [benfred/py-spy#246]
py-spy crashed when using it from the Host OS to profile a running process running inside the docker container.

```bash
# py-spy --version
py-spy 0.4.0-dev0
# RUST_BACKTRACE=1 py-spy top -n -p 15133
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/python_spy.rs:246:68
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: py_spy::python_spy::PythonSpy::_get_stack_traces
  15: py_spy::python_spy::PythonSpy::retry_new
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: receiving on a closed channel
   0: failure::backtrace::internal::InternalBacktrace::new
   1: py_spy::sampler::Sampler::new
   2: py_spy::run_spy_command
   3: py_spy::main
   4: std::rt::lang_start::{{closure}}
   5: main
```

**Comment by messense** [comment]
With `py-spy 0.3.3`:

```bash
# RUST_BACKTRACE=1 py-spy top -n -p 15133
Error: Failed to get process executable name. Check that the process is running.
Reason: No such file or directory (os error 2)
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: <core::result::Result<T,E> as failure::result_ext::ResultExt<T,E>>::context
   3: py_spy::python_spy::PythonSpy::new
   4: py_spy::python_spy::PythonSpy::retry_new
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
```

**Comment by benfred** [comment]
Profiling from the host OS doesn't work right now with the '--native' option enabled. This issue is being tracked at https://github.com/benfred/py-spy/issues/214 .
