### ISSUE TITLE
Test fails on aarch64 Alpine Linux

### ISSUE THREAD

**Issue by messense** [benfred/py-spy#423]
https://gitlab.alpinelinux.org/messense/aports/-/jobs/438427

```bash
failures:
---- test_subprocesses_zombiechild stdout ----
thread 'test_subprocesses_zombiechild' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No python processes found in process 4465 or any of its subprocesses" }', tests/integration_test.rs:337:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- test_busy_loop stdout ----
thread 'test_busy_loop' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_local_vars stdout ----
thread 'test_local_vars' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_long_sleep stdout ----
thread 'test_long_sleep' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_unicode stdout ----
thread 'test_unicode' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_thread_names stdout ----
thread 'test_thread_names' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_negative_linenumber_increment stdout ----
thread 'test_negative_linenumber_increment' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_recursive stdout ----
thread 'test_recursive' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', tests/integration_test.rs:37:65
---- test_delayed_subprocess stdout ----
thread 'test_delayed_subprocess' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No python processes found in process 4451 or any of its subprocesses" }', tests/integration_test.rs:379:72
---- test_subprocesses stdout ----
thread 'test_subprocesses' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No python processes found in process 4463 or any of its subprocesses" }', tests/integration_test.rs:300:72
```

**Comment by benfred** [comment]
Hmm - I don't have an aarch64 box to test on =(.  The permission denied errors make me wonder though - is this related to docker? I notice in the log there that this CI system looks like its running a docker image, which will need some extra capabilities set .

**Comment by messense** [comment]
But it seems that x86_64 is also running in Docker without problem? https://gitlab.alpinelinux.org/messense/aports/-/jobs/450648
