### ISSUE TITLE
Panics at times when sampling a Django app

### ISSUE THREAD

**Issue by Salaah01** [benfred/py-spy#653]
Testing out py-spy locally the Django development server and so I have the following running:

```bash
python manage.py runserver 8001
```

I've then got `py-spy` running in a separate shell as sudo with the following args:

```bash
sudo venv/bin/py-spy record --duration 200 --rate 100 -p 10993 --output pyspy.svg --nonblocking
```

Now and again I get the following panic:

```bash
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', src/python_interpreters.rs:296:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/sampler.rs:218:22
```

Apologies if this has already been reported, I had a quick skim, but I didn't find it.

Some info about my system:

Processor: AMD Ryzen 9 7950X
RAM: 32GB
Main OS: Windows 10 but running on WSL 2
Python version of the running program: 3.11.7
py-spy version: 0.3.14

Let me know if you need any other info from me.

**Comment by sliedes** [comment]
Here's a backtrace I got. So far didn't manage yet to get a `RUST_BACKTRACE=full`. It sometimes works, sometimes hits this, and sometimes segfaults with the same target.

```
$ RUST_BACKTRACE=1 .../py-spy record -r 1000 -o profile.speedscope -f speedscope --idle --nonblocking -- python -m ...
py-spy> Sampling process 1000 times a second. Press Control-C to exit.

thread '<unnamed>' panicked at src/python_interpreters.rs:396:16:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:208:5
   3: py_spy::python_interpreters::read_varint
             at /home/sami/proj/chat/py-spy/src/python_interpreters.rs:396:16
   4: py_spy::python_interpreters::read_signed_varint
             at /home/sami/proj/chat/py-spy/src/python_interpreters.rs:405:24
   5: <py_spy::python_bindings::v3_11_0::PyCodeObject as py_spy::python_interpreters::CodeObject>::get_line_number
             at /home/sami/proj/chat/py-spy/src/python_interpreters.rs:461:33
   6: py_spy::stack_trace::get_line_number
             at /home/sami/proj/chat/py-spy/src/stack_trace.rs:224:8
   7: py_spy::stack_trace::get_stack_trace
             at /home/sami/proj/chat/py-spy/src/stack_trace.rs:141:46
   8: py_spy::python_spy::PythonSpy::_get_stack_traces
             at /home/sami/proj/chat/py-spy/src/python_spy.rs:241:29
   9: py_spy::python_spy::PythonSpy::get_stack_traces
             at /home/sami/proj/chat/py-spy/src/python_spy.rs:180:18
  10: py_spy::sampler::Sampler::new_sampler::{{closure}}
             at /home/sami/proj/chat/py-spy/src/sampler.rs:66:36
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src/sampler.rs:264:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: <py_spy::sampler::Sampler as core::ops::drop::Drop>::drop
             at /home/sami/proj/chat/py-spy/src/sampler.rs:264:13
   5: core::ptr::drop_in_place<py_spy::sampler::Sampler>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
   6: py_spy::record_samples
             at /home/sami/proj/chat/py-spy/src/main.rs:232:5
   7: py_spy::run_spy_command
             at /home/sami/proj/chat/py-spy/src/main.rs:378:13
   8: py_spy::pyspy_main
             at /home/sami/proj/chat/py-spy/src/main.rs:452:22
   9: py_spy::main
             at /home/sami/proj/chat/py-spy/src/main.rs:488:23
  10: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I think it may have something to do with the fairly large number of threads my app spawns (it has a thread pool of ~45 workers). It also uses asyncio.

The precise version I'm running is HEAD as of today (7cbbc015980c5db4d517b62523cf8488296fa2fd) with this added patch IIRC to help make more sense of some threaded code:

```diff
diff --git a/src/python_spy.rs b/src/python_spy.rs
index f5e36d6..e8c02da 100644
--- a/src/python_spy.rs
+++ b/src/python_spy.rs
@@ -347,6 +347,8 @@ impl PythonSpy {
         } else {
             let frame = &frames[0];
             (frame.name == "wait" && frame.filename.ends_with("threading.py"))
+                || (frame.name == "_worker" && frame.filename.ends_with("concurrent/futures/thread.py"))
+                || (frame.name == "_recv" && frame.filename.ends_with("multiprocessing/connection.py"))
                 || (frame.name == "select" && frame.filename.ends_with("selectors.py"))
                 || (frame.name == "poll"
                     && (frame.filename.ends_with("asyncore.py")
```

**Comment by humbertogontijo** [comment]
Any updated on this? Like @sliedes I also use some threads

**Comment by Jiehong** [comment]
I get a similar issue with python 3.11 and py-spy 0.3.14 (without django, byt just by using pyroscope-io on a python project).

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.3.14/src/python_interpreters.rs:302:16:
index out of bounds: the len is 71 but the index is 71
```

**Comment by jorge-menjivar** [comment]
I am also having this issue

**Comment by eth2353** [comment]
Same thing happening on Python 3.12.5 + py-spy v0.4.0 (through grafana/pyroscope-rs)

Two full backtraces:

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/python_interpreters.rs:257:16:
index out of bounds: the len is 25 but the index is 25
stack backtrace:
   0:     0xffff872590e4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb96435122ab7425b
   1:     0xffff87010cfc - core::fmt::write::h7c561ca7c8433f95
   2:     0xffff87232288 - std::io::Write::write_fmt::hf7d9a5a24b8e20d9
   3:     0xffff87259e74 - std::panicking::default_hook::{{closure}}::hede73113e98cf4b8
   4:     0xffff8725ad08 - std::panicking::rust_panic_with_hook::hd458a5a67c8fc44a
   5:     0xffff8725a79c - std::panicking::begin_panic_handler::{{closure}}::h4b3f096abbb4f13c
   6:     0xffff8725a718 - std::sys::backtrace::__rust_end_short_backtrace::hf33da5adf3f15f28
   7:     0xffff8725a70c - rust_begin_unwind
   8:     0xffff86fd43b8 - core::panicking::panic_fmt::hbb2cf5b22d399018
   9:     0xffff86fd4388 - core::panicking::panic_bounds_check::h5d39480915164959
  10:     0xffff87082c5c - <py_spy::python_bindings::v3_12_0::PyCodeObject as py_spy::python_interpreters::CodeObject>::get_line_number::h4e7f87f8cf73e1ff
  11:     0xffff8709a6c0 - py_spy::stack_trace::get_stack_trace::hfee8abc8960c3ddc
  12:     0xffff8708ccc0 - py_spy::python_spy::PythonSpy::get_stack_traces::hd157300e6e6f4f52
  13:     0xffff870c45a4 - std::sys::backtrace::__rust_begin_short_backtrace::h22e22df6e148cd78
  14:     0xffff870c41b8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h42a8748180c047bc
  15:     0xffff8725bf30 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1aa6598848bc871
  16:     0xffff890eee58 - <unknown>
  17:     0xffff89157f9c - <unknown>
  18:                0x0 - <unknown>
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/sampler.rs:264:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0:     0xffff872590e4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb96435122ab7425b
   1:     0xffff87010cfc - core::fmt::write::h7c561ca7c8433f95
   2:     0xffff87232288 - std::io::Write::write_fmt::hf7d9a5a24b8e20d9
   3:     0xffff87259e74 - std::panicking::default_hook::{{closure}}::hede73113e98cf4b8
   4:     0xffff8725ad08 - std::panicking::rust_panic_with_hook::hd458a5a67c8fc44a
   5:     0xffff8725a79c - std::panicking::begin_panic_handler::{{closure}}::h4b3f096abbb4f13c
   6:     0xffff8725a718 - std::sys::backtrace::__rust_end_short_backtrace::hf33da5adf3f15f28
   7:     0xffff8725a70c - rust_begin_unwind
   8:     0xffff86fd43b8 - core::panicking::panic_fmt::hbb2cf5b22d399018
   9:     0xffff86fd4670 - core::result::unwrap_failed::h0e2262a7feb8dc1d
  10:     0xffff870fc334 - core::ptr::drop_in_place<core::iter::adapters::take_while::TakeWhile<py_spy::sampler::Sampler,<pyroscope_pyspy::Pyspy as pyroscope::backend::backend::Backend>::initialize::{{closure}}::{{closure}}>>::h9b462ff5a5d692ef
  11:     0xffff870faf58 - std::sys::backtrace::__rust_begin_short_backtrace::h76c1629896ecf4f9
  12:     0xffff870f77d8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf4eaa0fa66fe2f7f
  13:     0xffff8725bf30 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1aa6598848bc871
  14:     0xffff890eee58 - <unknown>
  15:     0xffff89157f9c - <unknown>
  16:                0x0 - <unknown>
```

```
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/python_interpreters.rs:257:16:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0:     0xffff7d3e90e4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb96435122ab7425b
   1:     0xffff7d1a0cfc - core::fmt::write::h7c561ca7c8433f95
   2:     0xffff7d3c2288 - std::io::Write::write_fmt::hf7d9a5a24b8e20d9
   3:     0xffff7d3e9e74 - std::panicking::default_hook::{{closure}}::hede73113e98cf4b8
   4:     0xffff7d3ead08 - std::panicking::rust_panic_with_hook::hd458a5a67c8fc44a
   5:     0xffff7d3ea79c - std::panicking::begin_panic_handler::{{closure}}::h4b3f096abbb4f13c
   6:     0xffff7d3ea718 - std::sys::backtrace::__rust_end_short_backtrace::hf33da5adf3f15f28
   7:     0xffff7d3ea70c - rust_begin_unwind
   8:     0xffff7d1643b8 - core::panicking::panic_fmt::hbb2cf5b22d399018
   9:     0xffff7d164388 - core::panicking::panic_bounds_check::h5d39480915164959
  10:     0xffff7d212c5c - <py_spy::python_bindings::v3_12_0::PyCodeObject as py_spy::python_interpreters::CodeObject>::get_line_number::h4e7f87f8cf73e1ff
  11:     0xffff7d22a6c0 - py_spy::stack_trace::get_stack_trace::hfee8abc8960c3ddc
  12:     0xffff7d21ccc0 - py_spy::python_spy::PythonSpy::get_stack_traces::hd157300e6e6f4f52
  13:     0xffff7d2545a4 - std::sys::backtrace::__rust_begin_short_backtrace::h22e22df6e148cd78
  14:     0xffff7d2541b8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h42a8748180c047bc
  15:     0xffff7d3ebf30 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1aa6598848bc871
  16:     0xffff7f27ee58 - <unknown>
  17:     0xffff7f2e7f9c - <unknown>
  18:                0x0 - <unknown>
thread '<unnamed>' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/py-spy-0.4.0/src/sampler.rs:264:22:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0:     0xffff7d3e90e4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb96435122ab7425b
   1:     0xffff7d1a0cfc - core::fmt::write::h7c561ca7c8433f95
   2:     0xffff7d3c2288 - std::io::Write::write_fmt::hf7d9a5a24b8e20d9
   3:     0xffff7d3e9e74 - std::panicking::default_hook::{{closure}}::hede73113e98cf4b8
   4:     0xffff7d3ead08 - std::panicking::rust_panic_with_hook::hd458a5a67c8fc44a
   5:     0xffff7d3ea79c - std::panicking::begin_panic_handler::{{closure}}::h4b3f096abbb4f13c
   6:     0xffff7d3ea718 - std::sys::backtrace::__rust_end_short_backtrace::hf33da5adf3f15f28
   7:     0xffff7d3ea70c - rust_begin_unwind
   8:     0xffff7d1643b8 - core::panicking::panic_fmt::hbb2cf5b22d399018
   9:     0xffff7d164670 - core::result::unwrap_failed::h0e2262a7feb8dc1d
  10:     0xffff7d28c334 - core::ptr::drop_in_place<core::iter::adapters::take_while::TakeWhile<py_spy::sampler::Sampler,<pyroscope_pyspy::Pyspy as pyroscope::backend::backend::Backend>::initialize::{{closure}}::{{closure}}>>::h9b462ff5a5d692ef
  11:     0xffff7d28af58 - std::sys::backtrace::__rust_begin_short_backtrace::h76c1629896ecf4f9
  12:     0xffff7d2877d8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf4eaa0fa66fe2f7f
  13:     0xffff7d3ebf30 - std::sys::pal::unix::thread::Thread::new::thread_start::hc1aa6598848bc871
  14:     0xffff7f27ee58 - <unknown>
  15:     0xffff7f2e7f9c - <unknown>
  16:                0x0 - <unknown>
```
