### ISSUE TITLE
Appears to leave venv in bad state after failed install

### ISSUE THREAD

**Issue by dimaqq** [benfred/py-spy#69]
I couldn't install from source:

```
> pip install git+https://github.com/benfred/py-spy
Collecting git+https://github.com/benfred/py-spy
  Cloning https://github.com/benfred/py-spy to /private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6
Installing collected packages: py-spy
  Running setup.py install for py-spy ... error
    Complete output from command /Users/xxx/pipenv-profile/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-record-7usoih_4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xxx/pipenv-profile/include/site/python3.7/py-spy:
    running install
    running build
    running install_egg_info
    running egg_info
    creating py_spy.egg-info
    writing py_spy.egg-info/PKG-INFO
    writing dependency_links to py_spy.egg-info/dependency_links.txt
    writing top-level names to py_spy.egg-info/top_level.txt
    writing manifest file 'py_spy.egg-info/SOURCES.txt'
    reading manifest file 'py_spy.egg-info/SOURCES.txt'
    writing manifest file 'py_spy.egg-info/SOURCES.txt'
    Copying py_spy.egg-info to /Users/xxx/pipenv-profile/lib/python3.7/site-packages/py_spy-0.1.9-py3.7.egg-info
    running install_scripts
    writing list of installed files to '/private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-record-7usoih_4/install-record.txt'
    sh: cargo: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6/setup.py", line 100, in <module>
        zip_safe=False)
      File "/Users/xxx/pipenv-profile/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6/setup.py", line 68, in run
        raise ValueError("Failed to compile!")
    ValueError: Failed to compile!

    ----------------------------------------
Command "/Users/xxx/pipenv-profile/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-record-7usoih_4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xxx/pipenv-profile/include/site/python3.7/py-spy" failed with error code 1 in /private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/pip-req-build-viyrzhw6/
```

And then when I tried to force load a wheel, it turned out that package was marked as installed 😖 

```
> pip uninstall py-spy
Uninstalling py-spy-0.1.9:
  Would remove:
    /Users/xxx/pipenv-profile/lib/python3.7/site-packages/py_spy-0.1.9-py3.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled py-spy-0.1.9
```

**Comment by benfred** [comment]
Thanks for reporting this,

I agree that installing from source with setup.py isn't the best experience. You will need to have rust (and cargo) installed to get it going, and the setup.py here will do nothing to help you install those =(.

That last commit there should fix so that you won't need to uninstall after it fails - but it still won't build until you've installed cargo.

I've provided binary wheels for most major supported platforms so that you don't need to do a source install in most cases (and using cargo directly when doing a source install might be better than using the setup.py wrapper).
